import type { Metadata } from "next";

import "./globals.css";



export const metadata: Metadata = {
  title: "Portfolio Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="m-0 box-border p-0"
      >
        {children}
      </body>
    </html>
  );
}
